services:
  backend:
    # Jan 29 2026
    image: ghcr.io/get-convex/convex-backend:c0842a7e3f49ca7fac4ad161141c5587346e226a
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${PORT:-3210}:3210"
      - "${SITE_PROXY_PORT:-3211}:3211"
    volumes:
      - /var/lib/turbo-repo-astro-starter/convex-data:/convex/data

    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 10s

  dashboard:
    image: ghcr.io/get-convex/convex-dashboard:c0842a7e3f49ca7fac4ad161141c5587346e226a
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    depends_on:
      backend:
        condition: service_healthy
